ALTER TABLE accommodations
ADD COLUMN IF NOT EXISTS address VARCHAR(255) NULL,
ADD COLUMN IF NOT EXISTS property_type VARCHAR(50) NULL,
ADD COLUMN IF NOT EXISTS unit_count INT NULL,
ADD COLUMN IF NOT EXISTS has_ac TINYINT(1) DEFAULT 0,
ADD COLUMN IF NOT EXISTS has_parking TINYINT(1) DEFAULT 0,
ADD COLUMN IF NOT EXISTS has_room_service TINYINT(1) DEFAULT 0,
ADD COLUMN IF NOT EXISTS has_private_wc TINYINT(1) DEFAULT 0;
